apiVersion: batch/v1
kind: CronJob

metadata:
  name: recommendation-collector
  namespace: optimizer

spec:

  schedule: "*/1 * * * *"

  # Never start a new collector if the previous one is still running
  concurrencyPolicy: Forbid

  # Keep only the last 2 successful jobs
  successfulJobsHistoryLimit: 2

  # Keep only the last 2 failed jobs
  failedJobsHistoryLimit: 2

  jobTemplate:

    spec:

      # Delete finished jobs automatically after 60 seconds
      ttlSecondsAfterFinished: 60

      template:

        spec:

          serviceAccountName: recommendation-collector-sa

          restartPolicy: OnFailure

          containers:

          - name: recommendation-collector

            image: 085351677198.dkr.ecr.ap-south-1.amazonaws.com/recommendation-collector:latest

            imagePullPolicy: Always

            env:

            - name: BACKEND_URL

              value: "http://k8s-cost-optimizer-service:9000"